blank_issues_enabled: true
issue_template:
  = "chore-request.yml"
  - "feature-request.yml"
  - "bug-report.yml"
  - "security-report.yml"
contact_links:
  - name: "ðŸŽŠ Chill Viking Discussions"
    url: https://github.com/orgs/chill-viking/discussions
    about: Please ask and answer questions here.
